apiVersion: batch/v1
kind: Job
metadata:
  namespace: example05
  name: enable-alerts
  annotations:
    argocd.argoproj.io/sync-wave: "110" 
spec:
  template:
    spec:
      containers:
      - name: dummy-run
        image: alpine
        command:
          - "sleep"
          - "10"
      restartPolicy: Never
  backoffLimit: 2    
