apiVersion: batch/v1
kind: Job
metadata:
  namespace: example05
  name: grafana-notify-success
  annotations:
    argocd.argoproj.io/sync-wave: "-10" 
spec:
  template:
    spec:
      containers:
      - name: dummy-run
        image: alpine
        command:
          - "sleep"
          - "8"
      restartPolicy: Never
  backoffLimit: 2    
