apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  type: ClusterIP
  selector:
    app: trivial-go-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
