apiVersion: batch/v1
kind: Job
metadata:
  namespace: example05
  name: send-slack-message
  annotations:
    argocd.argoproj.io/sync-wave: "230" 
spec:
  template:
    spec:
      containers:
      - name: dummy-run
        image: alpine
        command:
          - "sleep"
          - "5"
      restartPolicy: Never
  backoffLimit: 2    
